### PR TITLE
Deprecation documentation in JSDocs

### LINKED ISSUE #2750: Formatters.RelativeDate - Warns deprecation, API doesnt say so
When you instantiate a Formatters.RelativeDate, it prints a warning to console saying that it's deprecated. However, the API docs don't say this, so someone reading http://plottablejs.org/docs/modules/plottable.formatters.html may think it's fine to depend on.

As an aside, a relative date formatter seems useful to have, does it really make sense to deprecate it due to a bug? As opposed to just fixing the bug? My impression is you deprecate things because they are the wrong api, not because they have a bad implementation. Or is the API for RelativeDate formatter fundamentally unworkable because they don't get the TZ info from js date objects? I never really grokked time zones.

### PR DESCRIPTION
**Pull request by aicioara**
Closes #2750

- Added better deprecated documentation for deprecated methods
- Synced the versioning number between existing comments and the `deprecate()` method
- Added missing deprecation messages

### CODE REVIEW

File: src/core/formatters.ts [hunk 1]
```diff
@@ -244,6 +244,8 @@ export module Formatters {
   }
 
   /**
+   * @deprecated As of release 1.3.0, not safe for use with time zones.
+   *
```
Comment (bluong) [inline src/core/formatters.ts]: Let's make the deprecated call take "1.3.0"?

File: src/plots/barPlot.ts [hunk 2]
```diff
@@ -313,8 +313,11 @@ export module Plots {
       return closest;
     }
 
+    /**
+     * @deprecated As of release 1.1.0, replaced by _entityVisibleOnPlot()
+     */
     protected _visibleOnPlot(datum: any, pixelPoint: Point, selection: d3.Selection<void>): boolean {
-      Utils.Window.deprecated("Bar._visibleOnPlot()", "v1.1.0");
+      Utils.Window.deprecated("Bar._visibleOnPlot()", "v1.1.0", "replaced by _entityVisibleOnPlot()");
```
Comment (bluong) [inline src/plots/barPlot.ts]: Should there be a "v" in front of the version number?

File: src/plots/plot.ts [hunk 3]
```diff
@@ -544,8 +544,11 @@ export class Plot extends Component {
     return this._lightweightPlotEntityToPlotEntity(closestPointEntity);
   }
 
+  /**
+   * @deprecated As of release 1.1.0, replaced by _entityVisibleOnPlot()
+   */
   protected _visibleOnPlot(datum: any, pixelPoint: Point, selection: d3.Selection<void>): boolean {
-    Utils.Window.deprecated("Plot._visibleOnPlot()", "v1.1.0");
+    Utils.Window.deprecated("Plot._visibleOnPlot()", "v1.1.0", "replaced by _entityVisibleOnPlot()");
```
Comment (bluong) [inline src/plots/plot.ts]: Same as above

File: src/plots/scatterPlot.ts [hunk 4]
```diff
@@ -93,8 +93,11 @@ export module Plots {
       return drawSteps;
     }
 
+    /**
+     * @deprecated As of release 1.1.0, replaced by _entityVisibleOnPlot()
+     */
     protected _visibleOnPlot(datum: any, pixelPoint: Point, selection: d3.Selection<void>): boolean {
-      Utils.Window.deprecated("Scatter._visibleOnPlot()", "v1.1.0");
+      Utils.Window.deprecated("Scatter._visibleOnPlot()", "v1.1.0", "replaced by _entityVisibleOnPlot()");
```
Comment (bluong) [inline src/plots/scatterPlot.ts]: Same as above

**Comment by aicioara** [comment]
[NOQE] Only comments and warning messages have changed.

@bluong thoughts?
