### PR TITLE
Sanitize newlines in category scale domains

### LINKED ISSUE #2958: [Axes.Category] Blows up when passed newlines
`Axes.Category` fails to render when its `Scale` has domain values that include newline characters (`\n`).

**repro**: http://jsfiddle.net/fw39ca6q/
**actual**: Nothing is drawn, and `Uncaught Error: SingleLineWrapper is designed to work only on single line` appears in the console.
**expected**: `Axes.Category` either:
* Ignores the newlines, replacing them with spaces
* respects the newlines if possible

### PR DESCRIPTION
**Pull request by TheBeruriahIncident**
**Issue:** Newlines in the domain of category scale would cause an exception, as the category axis uses SingleLineWrapper.
**Fix:** The more general Wrapper (not SingleLineWrapper) is used.

**Before:** https://jsfiddle.net/ux9w72do/
**After:** https://jsfiddle.net/yvaayb38/

Close #2958

### CODE REVIEW

File: src/scales/categoryScale.ts [hunk 1]
```diff
@@ -142,7 +142,14 @@ module Plottable.Scales {
...
     protected _getDomain() {
-      return this._d3Scale.domain();
+      let newlineRemover = function(domain) {
+        if (typeof domain !== "string") {
+          return domain;
+        }
+        return domain.replace(/\n/g, " ");
+      };
+
+      return this._d3Scale.domain().map(newlineRemover);
```
Comment (jtlan) [inline src/scales/categoryScale.ts]: I'm not sure it's a good idea to modify the domain. This change would produce some unexpected behavior:
```Javascript
var originalDomain = ["two\nlines"];
categoryScale.domain(originalDomain);
assert.deepEqual(categoryScale.domain(), originalDomain); // fails
```

**Comment by jtlan** [comment]
It seems like an easier way to fix this is to change `_wrapper` in `Axes.Category` to a `SVGTypewriter.Wrappers.Wrapper` instead of a `SVGTypewriter.Wrappers.SingeLineWrapper`, which also has the benefit of preserving the user-inserted newlines.

**Comment by crmorford** [comment]
i wonder if this fixes #1998 in addition to #2958 (will test)

**Comment by jtlan** [comment]
Probably won't fix #1998, because that would require a change to `Legend`. Maybe `Legend` is best served by the original fix (replace newlines with spaces)?

**Comment by crmorford** [comment]
some examples: http://jsfiddle.net/fw39ca6q/1/
