### PR TITLE
Component.Group now occupies all offered space

### LINKED ISSUE #1791: Grouping fixed-size Components produces unexpected behavior
Chart with an `Axis` at the bottom: http://jsfiddle.net/yzfauLe7/
screen shot 2015-04-03 at 1 29 49 pm

Chart with a `Label` at the bottom: http://jsfiddle.net/yzfauLe7/1/
screen shot 2015-04-03 at 1 30 25 pm

Chart with `Group` containing an `Axis` and a `Label`: http://jsfiddle.net/yzfauLe7/2/
screen shot 2015-04-03 at 1 31 14 pm

????

### PR DESCRIPTION
**Pull request by jtlan**
This change causes `Component.Group` to behave as though it's not there by occupying the entirety of any space in the final offer, although it will still request no more space than is necessary to fit its `Components`.

Close #1791.
Also should not break #1255.

### CODE REVIEW

File: src/components/componentGroup.ts [hunk 1]
```diff
@@ -49,12 +49,17 @@ export module Component {
...
+      this._height = availableHeight;
+    }
+
     public _isFixedWidth(): boolean {
-      return false;
+      return this.components().every((c) => c._isFixedWidth());
     }
 
     public _isFixedHeight(): boolean {
-      return false;
```
Comment (bluong) [inline src/components/componentGroup.ts]: What happens in the case of alignments?

File: test/core/componentGroupTests.ts [hunk 2]
```diff
@@ -164,32 +126,54 @@ describe("ComponentGroups", () => {
...
+      ]);
+
+      var request = cg._requestedSpace(SVG_WIDTH, SVG_HEIGHT);
+      verifySpaceRequest(request, 0, 0, false, false, "empty Group doesn't request any space");
+
+      cg.renderTo(svg);
+      assert.strictEqual(cg.width(), SVG_WIDTH, "occupies all offered width");
+      assert.strictEqual(cg.height(), SVG_HEIGHT, "occupies all offered height");
+      svg.remove();
     });
```
Comment (bluong) [inline test/core/componentGroupTests.ts]: How does this work with a proportional idea?

File: test/core/componentGroupTests.ts [hunk 3]
```diff
@@ -164,32 +126,54 @@ describe("ComponentGroups", () => {
...
+
+      var request = cg._requestedSpace(SVG_WIDTH, SVG_HEIGHT);
+      assert.strictEqual(request.width, SVG_WIDTH/2, "requested enough space for widest Component");
+      assert.strictEqual(request.height, SVG_HEIGHT/2, "requested enough space for tallest Component");
+
+      cg.renderTo(svg);
+      assert.strictEqual(cg.width(), SVG_WIDTH, "occupies all offered width");
+      assert.strictEqual(cg.height(), SVG_HEIGHT, "occupies all offered height");
+      svg.remove();
     });
```
Comment (bluong) [inline test/core/componentGroupTests.ts]: Can you write a test that describes the dragbox case?

**Comment by bluong** [comment]
Implementation looks fine.  Just some testing fixes

File: src/components/componentGroup.ts (hunk 1 above)
Comment (jtlan) [inline src/components/componentGroup.ts]: `Group` no longer accounts for the alignments of sub`Component`s. If it did, the resultant layout behavior would be dependent on the alignments, which is contrary to the goal of having `Group` behave as though it isn't there during layout.

Since the `Group` occupies the whole cell, its own alignment has no effect.

File: test/core/componentGroupTests.ts (hunk 2 above)
Comment (jtlan) [inline test/core/componentGroupTests.ts]: I should probably assert something about `_isFixedWidth()`. It doesn't request space, but it's non-fixed so it will accept more.

The problem is that this behavior really manifests when inside a `Table`, but that's more of an integration test.

File: test/core/componentGroupTests.ts (hunk 3 above)
Comment (jtlan) [inline test/core/componentGroupTests.ts]: Not yet, since `DragBoxLayer` has yet to merge. There aren't many `Component`s that don't participate in layout but occupy all space in the final offer ... other than `Group` itself.

File: test/core/componentGroupTests.ts (hunk 2 above)
Comment (bluong) [inline test/core/componentGroupTests.ts]: Oh I guess my main confusion was why the test was named "with proportional Components" when I see nothing really proportional about this test...?

File: test/core/componentGroupTests.ts (hunk 3 above)
Comment (bluong) [inline test/core/componentGroupTests.ts]: Well when I say the dragbox case, I mean create the scenario surrounding it (A group with something of fixed height and something that doesn't care about the space it's in) and see how that reacts

**Comment by bluong** [comment]
Just fix up the tests and this should be good to go

File: test/core/componentGroupTests.ts (hunk 3 above)
Comment (jtlan) [inline test/core/componentGroupTests.ts]: The "liquid" `Component`s are essentially fixed-size with 0 width and 0 height, but if they happened to be offered more in the final offer they will take it. Based on that, the test case `"with fixed-size Components"` should cover it.

File: plottable.js [hunk 4]
```diff
@@ -3485,15 +3485,18 @@ var Plottable;
                         throw new Error("null arguments cannot be passed to _computeLayout() on a non-root node");
                     }
                 }
-                var requestedSpace = this._requestedSpace(availableWidth, availableHeight);
-                this._width = this._isFixedWidth() ? Math.min(availableWidth, requestedSpace.width) : availableWidth;
-                this._height = this._isFixedHeight() ? Math.min(availableHeight, requestedSpace.height) : availableHeight;
+                this._setSize(availableWidth, availableHeight);
                 this._xOrigin = offeredXOrigin + this._xOffset + (availableWidth - this.width()) * this._xAlignProportion;
                 this._yOrigin = offeredYOrigin + this._yOffset + (availableHeight - this.height()) * this._yAlignProportion;
                 ;
```
Comment (bluong) [inline plottable.js]: Might as well remove this semicolon

File: src/components/abstractComponent.ts [hunk 5]
```diff
@@ -134,17 +134,19 @@ export module Component {
           throw new Error("null arguments cannot be passed to _computeLayout() on a non-root node");
         }
       }
-      var requestedSpace = this._requestedSpace(availableWidth, availableHeight);
-      this._width  = this._isFixedWidth()  ? Math.min(availableWidth , requestedSpace.width)  : availableWidth ;
-      this._height = this._isFixedHeight() ? Math.min(availableHeight, requestedSpace.height) : availableHeight;
-
+      this._setSize(availableWidth, availableHeight);
       this._xOrigin = offeredXOrigin + this._xOffset + (availableWidth - this.width()) * this._xAlignProportion;
       this._yOrigin = offeredYOrigin + this._yOffset + (availableHeight - this.height()) * this._yAlignProportion;;
```
Comment (bluong) [inline src/components/abstractComponent.ts]: There's an extra semicolon if you wanna take that out
