### PR TITLE
Safari test fix. ES6 Set forEach() badly implemented in Safari

### LINKED ISSUE #2353: Tests failing in Safari
There is 1 set test failing in Safari

### PR DESCRIPTION
**Pull request by aicioara**
Closes #2353

As [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/forEach) suggests, the second argument for the `forEach()` method is the same as the first argument. However, Safari is not following the spec, so had to add a HackHack for the test to pass.

### CODE REVIEW

**Comment by bluong** [comment]
How about for Mobile Safari?  How do `Set`s work there?  Do we need to change our implementation for our code to work there?

**Comment by aicioara** [comment]
It should work on mobile Safari as well, but testing now

**Comment by aicioara** [comment]
Tested in Safari mobile and it works

File: test/tests.js [hunk 1]
```diff
@@ -8341,7 +8341,10 @@ describe("Utils", function () {
             set.add(values[1]);
             var index = 0;
             set.forEach(function (value1, value2, passedSet) {
-                assert.strictEqual(value1, value2, "The two value arguments passed to the callback are the same");
+                // HACKHACK: Safari does not pass a duplicate value as the second argument, as the spec suggests.
+                if (value2 !== undefined) {
```
Comment (jtlan) [inline test/tests.js]: Can we have an `else` that tests the Safari implementation separately?

**Comment by jtlan** [comment]
Does this mean that our `forEach()` just doesn't work correctly on Safari?

File: test/tests.js (hunk 1 above)
Comment (aicioara) [inline test/tests.js]: It is covered. Safari has `value2 === undefined`. the else would look like
`typescript
else {
  assert.strictEqual(value2, undefined, "Safari")
}
```
which looks a bit silly

**Comment by aicioara** [comment]
It does not really matter because we don't use value 2 anyway. It was designed like that such that it is consistent with the Map API (argument1, argument2, callback). 

However, if we are to be pedantic then yes, `forEach` does not work the same on Safari as it does on FF and Chrome

File: test/tests.js (hunk 1 above)
Comment (aicioara) [inline test/tests.js]: Maybe I should amend the message of the hackhack, since it was not clear to you that safari passes undefined?

Comment (jtlan) [inline test/tests.js]: Does Safari Pass the `Set` as the third argument?

If there's a bug # for it on Safari, I would link that.

Comment (aicioara) [inline test/tests.js]: You are right, it does not pass the `Set` as the third argument either

Comment (aicioara) [inline test/tests.js]: 3rd argument does not matter. We have a wrapper for it anyway because we pass our own `Set`

**Comment by aicioara** [comment]
I opened bug #21489317 on Apple platform, but I have no idea how to see it from an external source

**Comment by jtlan** [comment]
[NOQE], test-only changes.
