### PR TITLE
[Plot] Graphs fail gracefully when presented with badly formatted data

### LINKED ISSUE #1848: [stackedArea] Graphs should fail gracefully when presented with badly formatted data
Easiest to comment on the JS fiddle
http://jsfiddle.net/d2te4yct/6/

- Graphs 1, 2 and 3 should be the same. "0" should be 0 and "s" should default to 0
- Graph 4 is not rendered until #1838 is merged. For discussion sake, in this jsfiddle http://jsfiddle.net/d2te4yct/7/ you can see that the blue area is not rendered at all (on the right hand side). Ideally we should have that area filled with `blue`

### PR DESCRIPTION
**Pull request by aicioara**
Closes #1848 #1850 #1851 

A couple of graphs, when presented with badly formatted data, were just exploding. We want to handle these cases more gracefully now. The ticket is about `Plot.StackedArea`, `Plot.Pie`, `Plot.Grid`

Plot.StackedArea
===
Before: http://jsfiddle.net/d2te4yct/10/
After: http://jsfiddle.net/d2te4yct/11/

Plot.Pie
===
Before: http://jsfiddle.net/vmzfzx88/3/
After: http://jsfiddle.net/vmzfzx88/4/

Plot.Grid
===
(difference here is more subtle, basically now nothing is thrown in the console)
Before: http://jsfiddle.net/wd1mmd38/
After: http://jsfiddle.net/wd1mmd38/1/

Added unit tests for each

Also, there is a discussion about `null` and `undefined` which should behave the same. That is a discussion for #1866

### CODE REVIEW

File: src/components/plots/abstractStackedPlot.ts [hunk 1]
```diff
@@ -122,7 +122,7 @@ export module Plot {
 
           var value = valueAccessor(datum, datumIndex, dataset.metadata(), plotMetadata);
           var offset: number;
-          if (value === 0) {
+          if (value === 0 || value === "0") {
```
Comment (jtlan) [inline src/components/plots/abstractStackedPlot.ts]: Should we be accepting stringy values?

File: src/drawers/arcDrawer.ts [hunk 2]
```diff
@@ -39,6 +39,9 @@ export module _Drawer {
     public draw(data: any[], drawSteps: DrawStep[], userMetadata: any, plotMetadata: Plot.PlotMetadata) {
       // HACKHACK Applying metadata should be done in base class
       var valueAccessor = (d: any, i: number) => drawSteps[0].attrToProjector["value"](d, i, userMetadata, plotMetadata);
+
+      data = data.filter(e => !!+valueAccessor(e, null));
```
Comment (jtlan) [inline src/drawers/arcDrawer.ts]: What does `!!` do?

File: src/components/plots/abstractStackedPlot.ts (hunk 1 above)
Comment (aicioara) [inline src/components/plots/abstractStackedPlot.ts]: Well, if we don't this is not the place to begin doing that. Shall I file a new issue about this? Keep in mind that `d3` scales accept strings as arguments, np

File: src/drawers/arcDrawer.ts (hunk 2 above)
Comment (aicioara) [inline src/drawers/arcDrawer.ts]: 1. It filters numbers other than 0, null, undefined, NaN, unCoercible strings. 
2. If the user wants to draw a slice with size 0, that's not drawn, correct? So filtering is not semantically correct, but achieves the same result

**Comment by crmorford** [comment]
ON stacked area, undefined and NaN make the whole data series not show up:
screen shot 2015-04-23 at 10 25 36 am
 but null causes a gross failure:
screen shot 2015-04-23 at 10 25 27 am
Can someone explain the reasoning why these are different?

**Comment by aicioara** [comment]
@crmorford Agree, the second graph is a bug, will fix that

**Comment by aicioara** [comment]
Fixed an issue and did not address any of the concerns above (however, check my comments)

File: src/components/plots/abstractStackedPlot.ts [hunk 3]
```diff
@@ -122,7 +122,7 @@ export module Plot {
 
           var value = valueAccessor(datum, datumIndex, dataset.metadata(), plotMetadata);
           var offset: number;
-          if (value === 0) {
+          if (!+value) {
             offset = isAllNegativeValues ? negativeOffset : positiveOffset;
           } else {
             offset = value > 0 ? positiveOffset : negativeOffset;
```
Comment (jtlan) [inline src/components/plots/abstractStackedPlot.ts]: Shouldn't we use the converted `value` here?

File: src/drawers/arcDrawer.ts (hunk 2 above)
Comment (jtlan) [inline src/drawers/arcDrawer.ts]: The slice is drawn, but it has size 0. A tooltip would still stick to it for example, but it wouldn't if the data wasn't there at all.

File: src/components/plots/rectanglePlot.ts [hunk 4]
```diff
@@ -36,12 +36,13 @@ export module Plot {
       var y2Attr = attrToProjector["y2"];
 
       // Generate width based on difference, then adjust for the correct x origin
-      attrToProjector["width"] = (d, i, u, m) => Math.abs(x2Attr(d, i, u, m) - x1Attr(d, i, u, m));
-      attrToProjector["x"] = (d, i, u, m) => Math.min(x1Attr(d, i, u, m), x2Attr(d, i, u, m));
+      attrToProjector["width"] = (d, i, u, m) => Math.abs(x2Attr(d, i, u, m) - x1Attr(d, i, u, m)) || 0;
+      attrToProjector["x"] = (d, i, u, m) => Math.min(x1Attr(d, i, u, m), x2Attr(d, i, u, m)) || 0;
```
Comment (jtlan) [inline src/components/plots/rectanglePlot.ts]: This has the exact opposite problem of the one in `Pie`: Illegal rectangles will be drawn as size 0, instead of being missing.

File: src/components/plots/abstractStackedPlot.ts (hunk 3 above)
Comment (aicioara) [inline src/components/plots/abstractStackedPlot.ts]: you mean 
```typescript 
+offset = value > 0 ? positiveOffset : negativeOffset;
```
I agree

**Comment by jtlan** [comment]
We have some mixups here regarding the effects of 0 and invalid data. Here's what should happen:
* Data that produces objects with `0` size (the angle on a `Pie` slice or the width/height of a `Bar` or `Rectangle`) should still be drawn on screen.
* Data with invalid values (`NaN`, `undefined`) shouldn't be drawn at all: There should be no DOM nodes associated with them.

**Comment by aicioara** [comment]
sounds fair. Looking into it

File: src/components/plots/rectanglePlot.ts (hunk 4 above)
Comment (jtlan) [inline src/components/plots/rectanglePlot.ts]: Maybe we do something like this?
```Typescript
var isValid = (d, i, u, m) => {
  return isValidNumber(x1Attr(d, i, u, m)) &&
         isValidNumber(x2Attr(d, i, u, m)) &&
         isValidNumber(y1Attr(d, i, u, m)) &&
         isValidNumber(x2Attr(d, i, u, m));
}
data.filter(isValid);
```

**Comment by aicioara** [comment]
Done all suggested changes

File: src/utils/utils.ts [hunk 5]
```diff
@@ -255,6 +255,14 @@ export module _Util {
     }
 
     /**
+     * Returns true if the argument is a number, which is not NaN
+     * Numbers represented as strings do not pass this function
+     */
+    export function isValidNumber(n: any) {
```
Comment (jtlan) [inline src/utils/utils.ts]: I was going to suggest naming this `isFiniteNumber`, but we might want to support infinite values alter, so I think `isValidNumber` is a good name.
