### PR TITLE
The batch datasets setter dispatches updates at the end in batch

### LINKED ISSUE #2418: Unnecessary quadratic slowdown when adding datasets to stacked plot
## Problem

If I have 150 datasets in `myDatasets`, and I call

``` javascript
new Plottable.Plots.StackedArea().datasets(myDatasets);
```

the resulting computation can take over 30 seconds on a powerful machine.
## Cause

The cause of this slow-down is that `.datasets` calls  `.addDataset` for each dataset, and every call to `.addDataset` ends up triggering a call to `Plottable.Utils.Stacking.stack`. Every call to `.stack` recomputes the stacking from scratch. It never takes more than ~0.3sec, but it's being called for every added dataset, so the time adds up.

_Stack trace:_

```
stack @ plottable.js:663
StackedArea._updateStackExtentsAndOffsets @ plottable.js:8124
StackedArea._updateExtentsForProperty @ plottable.js:8103
(anonymous function) @ plottable.js:6127
d3_class.forEach @ d3.js:341
Plot._updateExtents @ plottable.js:6127
Plot._onDatasetUpdate @ plottable.js:6035
Area._onDatasetUpdate @ plottable.js:7851
StackedArea._onDatasetUpdate @ plottable.js:8097
Plot.addDataset @ plottable.js:6015
Area.addDataset @ plottable.js:7860
(anonymous function) @ plottable.js:6228
Plot.datasets @ plottable.js:6228
```
## Proposed solution

The easiest way I can think of to fix this would be to add an additional argument to `.addDataset` called `suppressUpdates` (or something less silly). If provided, it would tell `.addDataset` not to call `._onDatasetUpdate()`. Then `.datasets` could choose to suppress updates and call `._onDatasetUpdate()` itself after all the datasets were added correctly.

Thoughts? I'd be happy to submit a PR myself, or to let someone else take care of this. :stuck_out_tongue:

### PR DESCRIPTION
**Pull request by aicioara**
Part of #2418 

Suggested improvements will come as separate PRs

150 Datasets (as requested) - Speedup `100x`
Before: http://jsfiddle.net/cn9x2p5j/2/ - `3300 ms`
After: http://jsfiddle.net/cn9x2p5j/3/ - `36 ms`

Affected (perf wise):
- Plot.datasets(). This method should be preferred for multiple datasets additions

Unaffected (perf wise):
- Plot.addDataset()
- Plot.removeDataset()

QE notes - affected points:
- Plot.datasets()
- Plot.destroy()
- Plot.addDataset()
- Plot.removeDataset()

QE notes - regression: 
- Everything should behave exactly the same

QE notes - performance: 
- Plot.datasets() should be 100x faster.
- Plot.destroy() should be faster
- Everything else should be exactly the same

### CODE REVIEW

**Comment by aicioara** [comment]
No tests added because functionally nothing changed.

**Comment by aicioara** [comment]
Also this is a straight improvement, so no new API endpoints have been added.

**Comment by aicioara** [comment]
Also moved the `addDatasets()` method lines closer to `datasets()` and `removeDataset()` (no idea why they were separated).

File: src/plots/plot.ts [hunk 1]
```diff
@@ -374,16 +353,50 @@ export class Plot extends Component {
...
    */
   public removeDataset(dataset: Dataset): Plot {
-    if (this.datasets().indexOf(dataset) > -1) {
-      this._removeDatasetNodes(dataset);
-      dataset.offUpdate(this._onDatasetUpdateCallback);
-      this._datasetToDrawer.delete(dataset);
+    return this._removeDataset(dataset, true);
+  }
+
+  private _removeDataset(dataset: Dataset, dispatchUpdate: boolean) {
```
Comment (bluong) [inline src/plots/plot.ts]: Instead of having a boolean parameter here, can we have this function not do any updating and then have `removeDataset()` do the updating manually?

File: src/plots/plot.ts [hunk 2]
```diff
@@ -374,16 +353,50 @@ export class Plot extends Component {
...
+   * Adds a Dataset to the Plot.
+   *
+   * @param {Dataset} dataset
+   * @returns {Plot} The calling Plot.
+   */
+  public addDataset(dataset: Dataset) {
+    return this._addDataset(dataset, true);
+  }
+
+  private _addDataset(dataset: Dataset, dispatchUpdate: boolean) {
```
Comment (bluong) [inline src/plots/plot.ts]: Instead of having a boolean parameter here, can we have this function not do any updating and then have `addDataset()` do the updating manually?

**Comment by bluong** [comment]
I was actually expecting a totally different solution to the quadratic problem, but this is a good solution as well.

This solution is specifically good since it batches all the dataset updates, which is great for general usage of `_onDatasetUpdate()`, however it does not help if the user were to add their datasets one-by-one.

Stacking is a process that luckily can be done incrementally (adding dataset 3 does not affect the stacking results for datasets 1/2) so I expected the answer to reside in our use of the stacking utils.

**Comment by bluong** [comment]
Let's rename the pull request title and description, as they are not descriptive.  This seems to be more aligned with "The batch datasets setter dispatches updates at the end in batch" or something similar.

**Comment by bluong** [comment]
Up to you if you want to do the incremental stacking but it is out of scope of this pull request

**Comment by aicioara** [comment]
Will do incremental stacking as well. Thanks for the suggestion.

**Comment by aicioara** [comment]
Changed my mind. Will do it in a separate PR. Will amend the rest and this is no longer closing the issue, but instead it is part of it.

File: src/plots/plot.ts [hunk 3]
```diff
@@ -93,29 +93,8 @@ export class Plot extends Component {
...
-    let drawer = this._createDrawer(dataset);
-    this._datasetToDrawer.set(dataset, drawer);
-
-    if (this._isSetup) {
-      this._createNodesForDataset(dataset);
-    }
-
-    dataset.onUpdate(this._onDatasetUpdateCallback);
+    this.datasets().forEach((dataset) => this._removeDataset(dataset));
     this._onDatasetUpdate();
```
Comment (bluong) [inline src/plots/plot.ts]: Instead why not
`this.datasets([]);`

**Comment by crmorford** [comment]
Great summary! thanks :)

**Comment by crmorford** [comment]
Something weird happening on Area 
http://jsfiddle.net/cn9x2p5j/4/
screen shot 2015-08-19 at 5 32 35 pm
and Stacked Area
http://jsfiddle.net/cn9x2p5j/5/
screen shot 2015-08-19 at 5 33 18 pm

**Comment by aicioara** [comment]
Thank you for catching that. Should be fixed now.

File: test/plots/piePlotTests.ts [hunk 4]
```diff
@@ -187,7 +187,8 @@ describe("Plots", () => {
           { value: 5000 },
           { value: 5000 }];
         let dataset = new Plottable.Dataset(data);
-        piePlot.addDataset(dataset).outerRadius(500);
+        piePlot.addDataset(dataset)
+        piePlot.outerRadius(500);
```
Comment (aicioara) [inline test/plots/piePlotTests.ts]: This is because addDataset returns `Plottable.Plot` now (notice the removal in the `Plottable.Plots.Pie`). 

Is this an API breaking change? If so the code I should add is.
```typescript
// this is in piePlot.ts
public addDataset(dataset: Dataset) {
  super.addDataset(dataset);
  return this;
```

File: test/plots/piePlotTests.ts [hunk 5]
```diff
@@ -187,7 +187,8 @@ describe("Plots", () => {
           { value: 5000 },
           { value: 5000 }];
         let dataset = new Plottable.Dataset(data);
-        piePlot.addDataset(dataset).outerRadius(500);
+        piePlot.addDataset(dataset);
+        piePlot.outerRadius(500);
```
Comment (aicioara) [inline test/plots/piePlotTests.ts]: This is because addDataset returns `Plottable.Plot` now (notice the removal in the `Plottable.Plots.Pie`). 

Is this an API breaking change? If so the code I should add is.
```typescript
// this is in piePlot.ts
public addDataset(dataset: Dataset) {
  super.addDataset(dataset);
  return this;
}
```

Comment (bluong) [inline test/plots/piePlotTests.ts]: For javascript no, for typescript yes even though the intention through typescript is visible.  I'd like to say that it's not an API breaking change, but we can do a quick survey.

**Comment by crmorford** [comment]
destroy b/a render is ok
speeds up removing too http://jsfiddle.net/cn9x2p5j/6/
regression pass looks good
