### PR TITLE
Barplot's pixelpoint return data point

### LINKED ISSUE #2793: [Plots.Bar] _pixelPoint() returns wrong value
The `_pixelPoint()` of `Plots.Bar` returns the wrong value:

screen shot 2015-09-21 at 3 59 52 pm
(green shows expected positions, red shows actual ones)

**Repro**: http://jsfiddle.net/8gxszz87/
**Actual**: points for negative values appear at the top of the bar, rather than the end.
**Expected**: return value for `_pixelPoint()` should match `entities().position`

It looks like `entities()` accounts for the wrong position somehow.

### PR DESCRIPTION
**Pull request by yunhaolucky**
**Issue** 
`entity.position` are used to calculate the nearest entity. It should return the data point calculated by scales (for stackedBarPlot, it should return data point plus offset). Previously, it returns wrong points when scale domain are reversed or bar datum values are negative. Also, `barPlot._pixelPoint()` should return the same result as `entity.position`.

**Fix** 
I change `barPlot._pixelPoint()` function and calculated `pixelPoint()` separately when the datum value is negative. Also, I also call`barPlot._pixelPoint()` inside `entity.position` to make them return the same point.
This fix should work in barPlot, stackedBarPlot and clusteredBarPlot.

**JSFiddle**:
`barPlot._pixelPoint()` vs `entity.position`
Before: http://jsfiddle.net/8gxszz87/1/
After: http://jsfiddle.net/yunhaolucky/8gxszz87/2/
(Red points are `_pixelPoint`, green points are `entity.position`).

`entity.position` returns wrong points
Before: http://jsfiddle.net/yunhaolucky/ogL16g2f/6/
After: http://jsfiddle.net/yunhaolucky/ogL16g2f/4/

close #2793 #2794

### CODE REVIEW

File: plottable.js [hunk 1]
```diff
@@ -630,7 +630,8 @@ var Plottable;
 var __extends = (this && this.__extends) || function (d, b) {
     for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
     function __() { this.constructor = d; }
-    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
```
Comment (bluong) [inline plottable.js]: Please update your typescript

File: src/plots/barPlot.ts [hunk 2]
```diff
@@ -720,8 +711,17 @@ export module Plots {
       let rectY = attrToProjector["y"](datum, index, dataset);
       let rectWidth = attrToProjector["width"](datum, index, dataset);
       let rectHeight = attrToProjector["height"](datum, index, dataset);
-      let x = this._isVertical ? rectX + rectWidth / 2 : rectX + rectWidth;
-      let y = this._isVertical ? rectY : rectY + rectHeight / 2;
+      let x: any;
+      let y: any;
```
Comment (bluong) [inline src/plots/barPlot.ts]: Are these `number`s?

File: src/plots/barPlot.ts [hunk 3]
```diff
@@ -290,8 +290,15 @@ export module Plots {
...
 
           // compute this bar's min and max along the secondary axis
-          let barMinSecondary = this._isVertical ? barBBox.y : barBBox.x;
-          let barMaxSecondary = barMinSecondary + (this._isVertical ? barBBox.height : barBBox.width);
+          let barMinSecondary: number;
+          let barMaxSecondary: number;
+          if (this._isVertical) {
+            barMinSecondary = barBBox.y - (entity.datum.y > this.baselineValue() ? 0 : barBBox.height);
+            barMaxSecondary = barBBox.y + (entity.datum.y > this.baselineValue() ? barBBox.height : 0);
+          }else {
```
Comment (bluong) [inline src/plots/barPlot.ts]: There should be a space before `else`

File: src/plots/barPlot.ts [hunk 4]
```diff
@@ -290,8 +290,15 @@ export module Plots {
...
+            barMinSecondary = barBBox.x - (entity.datum.x < this.baselineValue() ? 0 : barBBox.width);
+            barMaxSecondary = barBBox.x + (entity.datum.x < this.baselineValue() ? barBBox.width : 0);
+          }
```
Comment (bluong) [inline src/plots/barPlot.ts]: Can you explain the changes to `entitiesNearest()`?

File: test/plots/barPlotTests.ts [hunk 5]
```diff
@@ -252,8 +252,27 @@ describe("Plots", () => {
...
-        });
+          it("entities().position and pixelPoint() return the same point", () => {
+            let entities = barPlot.entities();
+            entities.forEach((entity) => {
+              let pixelPoint = (<any> barPlot)._pixelPoint(entity.datum, entity.index, entity.dataset);
+              assert.strictEqual(pixelPoint.x, entity.position.x, "pixelPoint and entities().position should have same x value");
+              assert.strictEqual(pixelPoint.y, entity.position.y, "pixelPoint and entities().position should have same y value");
+            });
+            svg.remove();
+          });
```
Comment (bluong) [inline test/plots/barPlotTests.ts]: I personally don't think this test is that useful.

`_pixelPoint` is a non-public function, which means that we are testing against pieces of the code that users will never touch.  While this may be useful if we really want to assert this, if the behavior derived from `_pixelPoint` were to work too, then we don't need to test this directly.

Also, there is some fragility here in that if `_pixelPoint` were to have its name changed, then we would get a runtime error since our compiler will not be able to catch the name change.

File: test/plots/barPlotTests.ts [hunk 6]
```diff
@@ -252,8 +252,27 @@ describe("Plots", () => {
...
 
+          it("entities().position returns the position of data point", () => {
+            let entities = barPlot.entities();
+            entities.forEach((entity) => {
+              let dataX = (<any> Plottable.Plot)._scaledAccessor(barPlot.x())(entity.datum, entity.index, entity.dataset);
+              let dataY = (<any> Plottable.Plot)._scaledAccessor(barPlot.y())(entity.datum, entity.index, entity.dataset);
```
Comment (bluong) [inline test/plots/barPlotTests.ts]: Instead of using `_scaledAccessor`, we could use the xScale/yScale with the xAccessor/yAccessor to check.

**Comment by bluong** [comment]
Can we put a description in the pull request such that readers of the pull request have better context?

**Comment by bluong** [comment]
One of the tests is testing a non-public function which has very limited use.

Also a question about `entitiesNearest()`

File: plottable.d.ts [hunk 7]
```diff
@@ -3357,8 +3357,8 @@ declare module Plottable {
             protected _getBarPixelWidth(): number;
             entities(datasets?: Dataset[]): PlotEntity[];
             protected _pixelPoint(datum: any, index: number, dataset: Dataset): {
```
Comment (bluong) [inline plottable.d.ts]: Let's explicitly type this as `Point`

**Comment by crmorford** [comment]
Testing Plan:
Regular/reversed xDomain for horizontal bar plots, stackedbar, clusteredbar
Regular/reversed yDomain for vertical bar plots, stackedbar, clusteredbar
category axes, linear, log
full regression pass

**Comment by crmorford** [comment]
vertical, clustered, flipped Y http://jsfiddle.net/ogL16g2f/8/

**Comment by crmorford** [comment]
develop: http://jsfiddle.net/ogL16g2f/9/
normal: http://jsfiddle.net/ogL16g2f/10/

stacked bar doesn't do well with a flipped domain :fearful: 
this could be the right place to fix that

**Comment by yunhaolucky** [comment]
The issue here is stackedBarPlot does draw bars correctly with a reversed scale domain. I open an issue about this #2830.

**Comment by bluong** [comment]
does or does not?
