### PR TITLE
[Interaction] Interaction fix

### LINKED ISSUE #2012: Detaching Interactions when they're already detached causes errors
Calling `detachFrom()` on an `Interaction` that's not currently attached to anything throws errors:

Repro: http://jsfiddle.net/zLerabxg/

**Actual**: An error appears in the console:
screen shot 2015-05-11 at 11 54 17 am
**Expected**: No error should be thrown, and nothing else should happen either.

Calling `detachFrom()` twice produces a slightly different error:
screen shot 2015-05-11 at 11 56 10 am
http://jsfiddle.net/zLerabxg/1/

### PR DESCRIPTION
**Pull request by aicioara**
Closes #2012
Calling `detachFrom` twice used to throw an error. Fixed the error and added comprehensive testing for the testcase. Waiting for a merge, then opening this up

Before 1: http://jsfiddle.net/zLerabxg/
After 1:http://jsfiddle.net/zLerabxg/2/

Before 2:http://jsfiddle.net/zLerabxg/1/
After 2: http://jsfiddle.net/zLerabxg/3/

### CODE REVIEW

File: src/interactions/interaction.ts [hunk 1]
```diff
@@ -44,7 +44,9 @@ module Plottable {
      * @return {Interaction}
      */
     public detachFrom(component: Component) {
-      this._unanchor();
+      if (this._isAnchored) {
```
Comment (jtlan) [inline src/interactions/interaction.ts]: Wouldn't it make more sense if this `if`-block encompassed all of the logic, rather than just `_unanchor()`? Although I don't really expect anything bad to happen.

Comment (aicioara) [inline src/interactions/interaction.ts]: Not really because we want detachFrom to revert the interaction to its original state (not be anchored to anything). Say this bit of code
```typescript
var interaction = new Plottable.Interaction();
var component = new Plottable.Component();
interaction.attachTo(component); // nothing anchored yet
interaction.detachFrom(component);

assert(interaction._componentAttachedTo === null)

Comment (jtlan) [inline src/interactions/interaction.ts]: I see, that makes sense.

File: test/interactions/interactionTests.ts [hunk 2]
```diff
@@ -71,6 +71,34 @@ describe("Interactions", () => {
...
+
+      assert.doesNotThrow(() => {
+        clickInteraction.detachFrom(component);
+      }, "Detaching an interaction which was not attached should not throw");
+
+      clickInteraction.attachTo(component);
+      clickInteraction.detachFrom(component);
+      assert.doesNotThrow(() => {
+        clickInteraction.detachFrom(component);
+      }, "calling detaching a component twice should not throw");
```
Comment (jtlan) [inline test/interactions/interactionTests.ts]: "calling detach() on a Component twice should not throw an error"

File: test/interactions/interactionTests.ts [hunk 3]
```diff
@@ -71,6 +71,34 @@ describe("Interactions", () => {
...
+
+      component.renderTo(svg);
+
+      clickInteraction.attachTo(component);
+      clickInteraction.detachFrom(component);
+      assert.doesNotThrow(() => {
+        clickInteraction.detachFrom(component);
+      }, "calling detaching a component twice should not throw even when attached to SVG");
```
Comment (jtlan) [inline test/interactions/interactionTests.ts]: "calling detachFrom() twice should not throw and error even if the Component is anchored"

File: test/interactions/interactionTests.ts [hunk 4]
```diff
@@ -71,6 +71,34 @@ describe("Interactions", () => {
       svg.remove();
     });
 
+    it("calling detachFrom on a detached Interaction has no effect", () => {
```
Comment (jtlan) [inline test/interactions/interactionTests.ts]: parens :(
