### PR TITLE
Stacked bar extent update

### LINKED ISSUE #1246: StackedBar on Dataset Change Does Not Scale Properly
Repro steps:
1. Observe initial state of stackedbar
2. Click on the chart to see changes in the first dataset with animation
3. StackedBar plot should have scaled properly in terms of y.
4. Click again to see the plot adjust itself properly

http://jsfiddle.net/tkim/xLrfhkzu/

screen shot 2014-10-24 at 12 10 35 pm

### PR DESCRIPTION
**Pull request by bluong**
Ensuring that offsets are calculated before the scale extents are updated.

Fixes #1246

### CODE REVIEW

File: src/components/plots/abstractStackedPlot.ts [hunk 1]
```diff
@@ -31,11 +31,11 @@ export module Plot {
     }
 
     public _onDatasetUpdate() {
-      super._onDatasetUpdate();
       // HACKHACK Caused since onDataSource is called before projectors are set up.  Should be fixed by #803
       if (this._datasetKeysInOrder && this._projections["x"]  && this._projections["y"]) {
```
Comment (jtlan) [inline src/components/plots/abstractStackedPlot.ts]: Was this fixed? #803 has long since been closed, as has its successor issue.

File: test/components/plots/stackedPlotTests.ts [hunk 2]
```diff
@@ -267,4 +267,56 @@ describe("Plots", () => {
...
+    it("extents are updated as datasets are updated", () => {
+      var data1 = [
+        { key: "a", value: 1 },
+        { key: "b", value: -2 }
+      ];
+      var data2 = [
+        { key: "a", value: 3 },
+        { key: "b", value: -4 }
+      ];
+      var data3 = [
```
Comment (jtlan) [inline test/components/plots/stackedPlotTests.ts]: Maybe name this `data2_b` or something to avoid confusion? Later there's this line
```Typescript
dataset2.data(data3);
```
which is confusing.

File: test/components/plots/stackedPlotTests.ts [hunk 3]
```diff
@@ -267,4 +267,56 @@ describe("Plots", () => {
...
+        { key: "a", value: 1 },
+        { key: "b", value: -2 }
+      ];
+
+      var dataset2 = new Plottable.Dataset(data2);
+      stackedBarPlot.addDataset("d1", data1);
+      stackedBarPlot.addDataset("d2", dataset2);
+
+      assert.closeTo(yScale.domain()[0], -6, 1, "test");
+      assert.closeTo(yScale.domain()[1], 4, 1, "test2");
```
Comment (jtlan) [inline test/components/plots/stackedPlotTests.ts]: Can we get more detailed test failure messages? These message get displayed when the test fails, so it's best if they signal to the dev what went wrong.

File: src/components/plots/abstractStackedPlot.ts (hunk 1 above)
Comment (bluong) [inline src/components/plots/abstractStackedPlot.ts]: I think so?  I'll send up a different PR to solve the HACKHACK

File: test/components/plots/stackedPlotTests.ts (hunk 3 above)
Comment (bluong) [inline test/components/plots/stackedPlotTests.ts]: Yep, this was probably due to bad self-review.  Will do.

File: test/components/plots/stackedPlotTests.ts (hunk 2 above)
Comment (bluong) [inline test/components/plots/stackedPlotTests.ts]: Agreed

**Comment by crmorford** [comment]
Looks good to me!
