### PR TITLE
fix pie chart selection bug

### LINKED ISSUE #2491: Mouse cursor position is not correct for pie chart selection.
The mouse cursor position does not correspond to the slice of the pie chart that is selected on click. The mouse cursor position is several pixels off and on click, selects either a different slice nearby or no slices at all.

Reproduce:
1. Create a pie chart with 5 slices - where one slice has a value of 500 and the other slices have values around 5.
2. Try to select one of the small slices.

See Slate ticket 2428

### PR DESCRIPTION
**Pull request by ztsai**
closes #2491

before: http://jsfiddle.net/pghLh8da/4/
after: http://jsfiddle.net/pghLh8da/3/

### CODE REVIEW

File: src/plots/piePlot.ts [hunk 1]
```diff
@@ -213,7 +213,7 @@ export module Plots {
       var center = { x: this.width() / 2, y: this.height() / 2 };
       var adjustedQueryPoint = { x: queryPoint.x - center.x, y: queryPoint.y - center.y };
       var radius = Math.sqrt(Math.pow(adjustedQueryPoint.x, 2) + Math.pow(adjustedQueryPoint.y, 2));
-      var angle = Math.acos(-adjustedQueryPoint.y / (1 + radius));
```
Comment (jtlan) [inline src/plots/piePlot.ts]: ... I thought this was suspicious the first time I saw it; @rcchen, what was the reasoning behind this?

File: src/plots/piePlot.ts [hunk 2]
```diff
@@ -213,7 +213,7 @@ export module Plots {
...
+      var angle = Math.acos(-adjustedQueryPoint.y / radius);
       if (adjustedQueryPoint.x < 0) {
         angle = Math.PI * 2 - angle;
       }
```
Comment (jtlan) [inline src/plots/piePlot.ts]: Instead of going through the trouble of using `acos()` followed by an if-check, could we use [`atan2()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2)?

File: src/plots/piePlot.ts (hunk 1 above)
Comment (rcchen) [inline src/plots/piePlot.ts]: https://github.com/palantir/plottable/pull/2340#discussion-diff-32654964

...I added instead of multiplied the two magnitudes...

Comment (rcchen) [inline src/plots/piePlot.ts]: Also https://github.com/palantir/plottable/blob/pieSelect/src/plots/piePlot.ts#L302

**Comment by ztsai** [comment]
talked about using ```atan2()``` offline; the range for the function is (-pi, pi], and it would still require a check to map the result to [0, 2*pi)

**Comment by bluong** [comment]
? the extent of both ranges is 2*pi.  Why can't we do a simple mapping from (-pi,pi] -> [0, 2*pi)

**Comment by jtlan** [comment]
>? the extent of both ranges is 2 * pi. Why can't we do a simple mapping from (-pi,pi] -> [0, 2*pi)

The origin and direction of the angles is different, I think.

**Comment by bluong** [comment]
In which case, we can still do a mapping no?

**Comment by crmorford** [comment]
Do we know why this was only happening on small slices, originally, and not larger ones?

**Comment by ztsai** [comment]
My guess is that the radius is only off by one pixel, so the wrong angel wouldn't off by a lot
