### PR TITLE
[SymbolDrawer] - Extends from ElementDrawer

### LINKED ISSUE #1771: Plot.Scatter shows invalid points
Malformed data is still drawn on `Plot.Scatter`:
screen shot 2015-03-26 at 3 22 04 pm
**Actual**: Big point drawn in upper-left corner, console shows "`Error: Invalid value for <path> attribute transform="translate(199.99999999999994,NaN) scale(0.06)"`"
**Expected**: Malformed data point is not drawn.

### PR DESCRIPTION
**Pull request by bluong**
`Drawer.Element` has functionality that should have been picked up in `Drawer.Symbol` but due to the lack of extension, that was unfortunately not picked up.  Now the hierarchy is made.

Fixes #1771

### CODE REVIEW

File: test/components/plots/scatterPlotTests.ts [hunk 1]
```diff
@@ -111,6 +111,40 @@ describe("Plots", () => {
...
+      var plot = new Plottable.Plot.Scatter(xScale, yScale);
+      plot.addDataset(dataset)
+          .project("x", "foo", xScale)
+          .project("y", "bar", yScale);
+      plot.renderTo(svg);
+
+      var dataWithNaN = data.slice();
+      dataWithNaN[2] = { foo: 0.4, bar: NaN };
+      dataset.data(dataWithNaN);
+      assert.strictEqual(plot.getAllSelections().size(), 4, "does not retrieve NaN point");
```
Comment (jtlan) [inline test/components/plots/scatterPlotTests.ts]: More accurately, "does not draw NaN point". Can we do this using direct D3 selection on `content()`, rather than using `getAllSelections()`, to make this independent?

File: src/drawers/symbolDrawer.ts [hunk 2]
```diff
@@ -2,23 +2,16 @@
...
-    private _getDrawSelection() {
-      return this._getRenderArea().selectAll("path");
+    constructor(key: string) {
+      super(key);
+      this._svgElement = "path";
+      this._className = "symbol";
     }
 
     protected _drawStep(step: AppliedDrawStep) {
-      super._drawStep(step);
```
Comment (jtlan) [inline src/drawers/symbolDrawer.ts]: No `super`?

Comment (bluong) [inline src/drawers/symbolDrawer.ts]: The `super` is moved to the end

File: test/components/plots/scatterPlotTests.ts (hunk 1 above)
Comment (bluong) [inline test/components/plots/scatterPlotTests.ts]: The most independent would technically be using raw D3/Javascript on the svg and then searching using svg.selectAll("path")...  Should we use that instead?

Comment (jtlan) [inline test/components/plots/scatterPlotTests.ts]: Maybe? I'm trying to flag that we're trying to assert that the point doesn't get drawn, which is subtly different from "doesn't get returned".
