### PR TITLE
[TimeAxis] Fixes overlap issues in TimeAxis

### LINKED ISSUE #1609: New fixes cause bad time axis behavior
On time axis, with GIANT font (100px), labels don't always disappear during panning when there isn't room for them.

screen shot 2015-02-09 at 5 54 48 pm
screen shot 2015-02-09 at 5 54 55 pm
screen shot 2015-02-09 at 5 55 03 pm
(panning this way --> )

http://jsfiddle.net/rndeLxo6/1/

### PR DESCRIPTION
**Pull request by rcchen**
Fixes #1609

### CODE REVIEW

File: src/components/axes/timeAxis.ts [hunk 1]
```diff
@@ -449,6 +449,26 @@ export module Axis {
...
       };
 
+      var visibleTickMarks = this._tierMarkContainers[index]
+                                    .selectAll("." + AbstractAxis.TICK_MARK_CLASS)
+                                    .filter(function(d: any, i: number) {
+                                      return d3.select(this).style("visibility") === "visible";
+                                    });
+
+      // We use the ClientRects because x1/x2 attributes are not comparable to ClientRects of labels
+      var visibleTickMarkRects = visibleTickMarks[0].map((mark: any) => mark.getBoundingClientRect() );
```
Comment (jtlan) [inline src/components/axes/timeAxis.ts]: `(mark: Element) =>` ?

**Comment by crmorford** [comment]
http://jsfiddle.net/rndeLxo6/2/
^ talked offline about a flicker

**Comment by rcchen** [comment]
Fiddle at http://jsfiddle.net/rndeLxo6/4/ is linked to this branch, flicker should be fixed.

File: src/components/axes/timeAxis.ts (hunk 1 above)
Comment (bluong) [inline src/components/axes/timeAxis.ts]: Try to avoid any wherever possible.  The only cases where we should have any's ideally is when dealing with raw data that we have no typing information for.

File: src/components/axes/timeAxis.ts [hunk 2]
```diff
@@ -449,17 +449,29 @@ export module Axis {
...
                                     });
       var lastLabelClientRect: ClientRect;
 
-      visibleTickLabels.each(function (d: any) {
+      visibleTickLabels.each(function (d: Element, i: number) {
         var clientRect = this.getBoundingClientRect();
         var tickLabel = d3.select(this);
-        if (!isInsideBBox(clientRect) || (lastLabelClientRect != null && _Util.DOM.boxesOverlap(clientRect, lastLabelClientRect))) {
+        var leadingTickMark = visibleTickMarkRects[i];
+        var trailingTickMark = visibleTickMarkRects[i+1];
```
Comment (jtlan) [inline src/components/axes/timeAxis.ts]: We might want to check the existence of these marks in case the number of visible tick marks is smaller than the number of labels (+1).

File: src/components/axes/timeAxis.ts [hunk 3]
```diff
@@ -449,17 +449,29 @@ export module Axis {
...
+        if (!isInsideBBox(clientRect) || (lastLabelClientRect != null && _Util.DOM.boxesOverlap(clientRect, lastLabelClientRect))
+            || (leadingTickMark.left > clientRect.left || trailingTickMark.left < clientRect.right)) {
```
Comment (jtlan) [inline src/components/axes/timeAxis.ts]: Probably want `leadingTickMark.right > clientRect.left`, to account for ticks with a thicker `stroke-width` property.

**Comment by jtlan** [comment]
Some concerns.

File: src/components/axes/timeAxis.ts (hunk 2 above)
Comment (rcchen) [inline src/components/axes/timeAxis.ts]: All visible tick labels will have a leading tick mark which will be visible. In addition, there is always a visible tick mark drawn at the end regardless, so there will always be n+1 visible ticks for n visible labels.

Comment (jtlan) [inline src/components/axes/timeAxis.ts]: Is there a difference between visible tick marks and the tick marks that are generated by default?

Comment (rcchen) [inline src/components/axes/timeAxis.ts]: Not afaik

**Comment by crmorford** [comment]
Looks good
