### PR TITLE
change tick label position and overlap method in timeAxis

### LINKED ISSUE #2772: Wrong Label Tick labels positions in 'top' orientation in Time Axis
The position of tick labels are set correctly when the orientation of axis is set to `top`. 

Repro: http://jsfiddle.net/o87wsq9h/2/
**Actual**: In this case, tick labels are hidden because their position are wrong and overlap with tick marks.
**Expected**: Tick labels should be visible when `orientation` is `top` and `tierLabelPositions` is `center`.

### PR DESCRIPTION
**Pull request by yunhaolucky**
**Issue**:
In a time axis with `top` orientation, the `y` value of label positions are not calculated correctly when its `tierlabelposition` is set to `center` . This is an issue because it makes tick marks overlap with tick labels and hide all labels as a result. 

**Fix**:
When calculate the `y` value of label positions, we do not consider the height of tick marks. I fix this.

**JSFiddle**:
Before:http://jsfiddle.net/o87wsq9h/2/
After:http://jsfiddle.net/o87wsq9h/3/

close #2772

### CODE REVIEW

File: src/axes/timeAxis.ts [hunk 1]
```diff
@@ -392,9 +392,14 @@ export module Axes {
...
-      let yTranslate = this.orientation() === "bottom" ?
-          d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding() :
-          this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding();
+      let yTranslate: number;
+      if (this.orientation() === "bottom") {
+        yTranslate = d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding();
+      } else if (this._tierLabelPositions[index] === "center") {
+          yTranslate = this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding() - this._maxLabelTickLength();
+      } else {
+          yTranslate = this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding();
```
Comment (bluong) [inline src/axes/timeAxis.ts]: Indentation above is inconsistent

File: test/axes/timeAxisTests.ts [hunk 2]
```diff
@@ -130,23 +130,62 @@ describe("TimeAxis", () => {
...
+      let svg = TestMethods.generateSVG(400, 100);
+      scale = new Plottable.Scales.Time();
+      scale.domain([new Date("2009-12-20"), new Date("2011-01-01")]);
+      axis = new Plottable.Axes.Time(scale, "bottom");
+      axis.renderTo(svg);
+      let tickRects = d3.selectAll("." + Plottable.Axis.TICK_MARK_CLASS)[0].map((mark: Element) => mark.getBoundingClientRect());
+      let labelRects = d3.selectAll("." + Plottable.Axis.TICK_LABEL_CLASS)
+          .filter(function(d, i) {
+            return d3.select(this).style("visibility") === "visible";
+          })[0].map((label: Element) => label.getBoundingClientRect());
```
Comment (bluong) [inline test/axes/timeAxisTests.ts]: use 2-space indentation

File: test/axes/timeAxisTests.ts [hunk 3]
```diff
@@ -130,23 +130,62 @@ describe("TimeAxis", () => {
...
+      labelRects.forEach(function(labelRect: ClientRect) {
+        tickRects.forEach(function(tickRect: ClientRect) {
+          assert.isFalse(Plottable.Utils.DOM.clientRectsOverlap(labelRect, tickRect), "visible label does not overlap with a tick");
+        });
       });
+      svg.remove();
+    });
+
+    function TickMarkAndLabelOverlap() {
```
Comment (bluong) [inline test/axes/timeAxisTests.ts]: function names should start with a lowercase

File: test/axes/timeAxisTests.ts [hunk 4]
```diff
@@ -130,23 +130,62 @@ describe("TimeAxis", () => {
...
+      let tickMarks = d3.selectAll(`.${Plottable.Axis.TICK_MARK_CLASS}:not(.${Plottable.Axis.END_TICK_MARK_CLASS})`);
+      assert.operator(tickMarks.size(), ">=", 1, "There is at least one tick mark in the test");
+      let tickLabels = d3.selectAll(`.${Plottable.Axis.TICK_LABEL_CLASS}`).filter(function(d, i) {
+          return window.getComputedStyle(this).visibility !== "hidden";
```
Comment (bluong) [inline test/axes/timeAxisTests.ts]: Why `window.getComputedStyle`?

File: test/axes/timeAxisTests.ts [hunk 5]
```diff
@@ -130,23 +130,62 @@ describe("TimeAxis", () => {
...
+      });
+      assert.operator(tickLabels.size(), ">=", 1, "There is at least one tick label in the test");
+      tickMarks.each(function(d, i) {
+        let tickMarkRect = this.getBoundingClientRect();
+        tickLabels.each(function(e, j) {
```
Comment (bluong) [inline test/axes/timeAxisTests.ts]: Let's rename the above variables  It is incredibly difficult to understand each piece without a good name

File: test/axes/timeAxisTests.ts (hunk 3 above)
Comment (bluong) [inline test/axes/timeAxisTests.ts]: Function name should be more telling.

If i were to call `TickMarkAndLabelOverlap()` this does not really tell the developer much.  It seems from the below you are making assertions.  In this case, you need to prepend "assert" into the function name or similar.

File: src/axes/timeAxis.ts [hunk 6]
```diff
@@ -392,9 +392,14 @@ export module Axes {
...
-          d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding() :
-          this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding();
+      let yTranslate: number;
+      if (this.orientation() === "bottom") {
+        yTranslate = d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding();
+      } else if (this._tierLabelPositions[index] === "center") {
+        yTranslate = this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding() - this._maxLabelTickLength();
+      } else {
+        yTranslate = this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding();
+      }
```
Comment (bluong) [inline src/axes/timeAxis.ts]: Just making sure, is "top" orientation unaffected?

File: src/axes/timeAxis.ts [hunk 7]
```diff
@@ -392,9 +392,14 @@ export module Axes {
...
       tickLabelsEnter.append("text");
       let xTranslate = (this._tierLabelPositions[index] === "center" || config.step === 1) ? 0 : this.tickLabelPadding();
-      let yTranslate = this.orientation() === "bottom" ?
-          d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding() :
-          this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding();
+      let yTranslate: number;
+      if (this.orientation() === "bottom") {
+        yTranslate = d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding();
+      } else if (this._tierLabelPositions[index] === "center") {
+        yTranslate = this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding() - this._maxLabelTickLength();
```
Comment (bluong) [inline src/axes/timeAxis.ts]: Can you explain this logic?

It seems that the first tier should be translated very close to the bottom which does not seem to make sense?

File: test/axes/timeAxisTests.ts [hunk 8]
```diff
@@ -130,23 +130,62 @@ describe("TimeAxis", () => {
...
+        });
       });
+      svg.remove();
+    });
+
+    function assertTickMarksAndLabelsDoNotOverlap() {
+      let tickMarks = d3.selectAll(`.${Plottable.Axis.TICK_MARK_CLASS}:not(.${Plottable.Axis.END_TICK_MARK_CLASS})`);
+      assert.operator(tickMarks.size(), ">=", 1, "There is at least one tick mark in the test");
+      let tickLabels = d3.selectAll(`.${Plottable.Axis.TICK_LABEL_CLASS}`).filter(function(d, i) {
+          return window.getComputedStyle(this).visibility !== "hidden";
```
Comment (bluong) [inline test/axes/timeAxisTests.ts]: Why `window.getComputedStyle(this)`?

File: src/axes/timeAxis.ts (hunk 7 above)
Comment (yunhaolucky) [inline src/axes/timeAxis.ts]: For axis with **bottom** orientation, each tier should be like
_____________
tick marks (if `tierLabelPostion` is `center`)
tickLabelPadding
LABEL
tickLabelPadding
______________

The height of each label's bottom line is the `height of next tier` - `tierLabelPdding()`. 


For axis with **top** orientation, each tier should be like
____________________

tickLabelPadding
LABEL
tickLabelPadding
tick marks(if `tierLabelPostion` is `center`)
____________________

The height of each label's bottom line is the tier's bottom line -  tickLabelPadding - the length of tickmarks (if the `tierLabelPostion` is `center`)

File: test/axes/timeAxisTests.ts (hunk 8 above)
Comment (yunhaolucky) [inline test/axes/timeAxisTests.ts]: Should I use `d3.style("visibility")` ?

Comment (bluong) [inline test/axes/timeAxisTests.ts]: That would be preferred

File: src/axes/timeAxis.ts (hunk 6 above)
Comment (bluong) [inline src/axes/timeAxis.ts]: Just curious, it does not seem that the center/top case is being considered.  If it is, it doesn't read to be so.  Can we have 2 `if` blocks?  One for standard orientation bottom vs top and then another to account for the center?

File: src/axes/timeAxis.ts [hunk 9]
```diff
@@ -392,9 +392,16 @@ export module Axes {
       let tickLabelsEnter = tickLabels.enter().append("g").classed(Axis.TICK_LABEL_CLASS, true);
       tickLabelsEnter.append("text");
       let xTranslate = (this._tierLabelPositions[index] === "center" || config.step === 1) ? 0 : this.tickLabelPadding();
-      let yTranslate = this.orientation() === "bottom" ?
-          d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding() :
-          this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding();
+      let yTranslate: number;
+      if (this.orientation() === "bottom") {
+        yTranslate = d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding();
+      } else { // this.orientation() === "top"
```
Comment (bluong) [inline src/axes/timeAxis.ts]: Comment is redundant.  please remove.

File: src/axes/timeAxis.ts [hunk 10]
```diff
@@ -392,9 +392,16 @@ export module Axes {
       let tickLabelsEnter = tickLabels.enter().append("g").classed(Axis.TICK_LABEL_CLASS, true);
       tickLabelsEnter.append("text");
       let xTranslate = (this._tierLabelPositions[index] === "center" || config.step === 1) ? 0 : this.tickLabelPadding();
-      let yTranslate = this.orientation() === "bottom" ?
-          d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding() :
-          this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding();
+      let yTranslate: number;
+      if (this.orientation() === "bottom") {
+        yTranslate = d3.sum(this._tierHeights.slice(0, index + 1)) - this.tickLabelPadding();
```
Comment (bluong) [inline src/axes/timeAxis.ts]: Does this calculation not change if the `_tierLabelPositions` is "center" instead of "between"?

File: src/axes/timeAxis.ts [hunk 11]
```diff
@@ -392,9 +392,16 @@ export module Axes {
...
+      } else { // this.orientation() === "top"
+        if (this._tierLabelPositions[index] === "center") {
+            yTranslate = this.height() - d3.sum(this._tierHeights.slice(0, index)) - this.tickLabelPadding() - this._maxLabelTickLength();
```
Comment (bluong) [inline src/axes/timeAxis.ts]: Indentation issues.

File: src/axes/timeAxis.ts (hunk 10 above)
Comment (yunhaolucky) [inline src/axes/timeAxis.ts]: Yes. For "bottom" orientation, the bottom lines of the labels are not affected by tick marks. This calculation works both for "center" and "between".

**Comment by crmorford** [comment]
with panzoom http://jsfiddle.net/o87wsq9h/9/
with custom (sloppy) config http://jsfiddle.net/o87wsq9h/10/
symmetrical with bottom axis? http://jsfiddle.net/o87wsq9h/11/
with annotations http://jsfiddle.net/o87wsq9h/12/
between still looks good http://jsfiddle.net/o87wsq9h/13/
