### PR TITLE
[Scales.Time] Change default extent to be wider and consistent.

### LINKED ISSUE #2740: Time Scale needs better default ticks
http://jsfiddle.net/korw10sr/
There are 2 ticks listed at the same location, so the time axis looks blank/broken when rendered without data.

### PR DESCRIPTION
**Pull request by jtlan**
Previously, the default extent was supposed to be based on the current day, but wound up defaulting instead to `[Unix epoch, + 1 second]`. The default extent has now been changed to be `[Unix epoch, + 1 day]`.

Close #2740.

### CODE REVIEW

File: src/scales/timeScale.ts [hunk 1]
```diff
@@ -12,6 +12,7 @@ export module Scales {
     constructor() {
       super();
       this._d3Scale = d3.time.scale();
+      this.autoDomain();
```
Comment (bluong) [inline src/scales/timeScale.ts]: Why autodomain on instantiation?

File: src/scales/timeScale.ts [hunk 2]
```diff
@@ -38,11 +39,7 @@ export module Scales {
     }
 
     protected _defaultExtent(): Date[] {
-      let now = new Date();
-      let endTimeValue = now.valueOf();
-      now.setDate(now.getDate() - 1);
-      let startTimeValue = now.valueOf();
-      return [new Date(startTimeValue), new Date(endTimeValue)];
+      return [new Date("1970-01-01"), new Date("1970-01-02")];
```
Comment (bluong) [inline src/scales/timeScale.ts]: Not a big deal, but I personally like the `(year, month, day)` constructor since I find it to be less error prone.

**Comment by bluong** [comment]
Just a question

File: src/scales/timeScale.ts (hunk 1 above)
Comment (jtlan) [inline src/scales/timeScale.ts]: To set the domain to padded `_defaultExtent()`. I guess we could test for it? It'd be kind of tautological though.
