### PR TITLE
Much faster entityNearest using a quadtree

### LINKED ISSUE #3307: Performance regressions on XYPlot.entityNearest
From gitter:

>  I have an XY chart with multiple datasets, and implement a tooltip. with beta.4 the performance started to get janky. Doing some profiling the hotspot looks like that in beta.2 the call to XYPlot.entityNearest was taking 0.5ms but with beta.4 the function is gone, and Plot.entityNearest takes 189ms (on same dataset)!!

### PR DESCRIPTION
**Pull request by themadcreator**
fixes #3307

### CODE REVIEW

**Comment by themadcreator** [comment]
This is SOOO much faster, but there are a couple more things to do

- [ ] Don't rebuild quadtree while panning
- [x] Fix tests (???)

**Comment by leebyp** [comment]
Note that for the 100k plot, the "rebuilding" of the tree is taking a good 400ms

EDIT: BAM! take out the getter which we don't need anymore because we nuke the cache, and it goes down to 40ms!

File: src/plots/plot.ts [hunk 1]
```diff
@@ -388,6 +388,7 @@ export class Plot extends Component {
    * Updates the extents associated with each attribute, then autodomains all scales the Plot uses.
    */
   protected _updateExtents() {
+    this._resetEntityStore();
```
Comment (leebyp) [inline src/plots/plot.ts:398]: why is this needed here now? isn't all we need done through the `scale.onUpdate`?

File: src/utils/entityStore.ts [hunk 2]
```diff
@@ -3,95 +3,90 @@
...
+export class EntityStore<T extends IPositionedEntity> implements IEntityStore<T> {
   private _entities: T[];
+  private _tree: d3.Quadtree<T>;
 
   constructor() {
     this._entities = [];
+    this._tree = d3.quadtree<T>()
+      // int casting for faster computation. losing sub-pixel precision here is
+      // of no concern.
+      .x((d) => d.position.x | 0)
```
Comment (hellochar) [inline src/utils/entityStore.ts]: nit: prefer Math.floor() to cast to int. Also do we know that casting to an int actually improves perf significantly?

File: src/utils/entityStore.ts [hunk 3]
```diff
@@ -3,95 +3,90 @@
...
+    this._entities.push(...entities);
+    this._tree.addAll(entities);
   }
 
   /**
-   * Iterates through array of of entities and computes the closest point using
-   * the standard Euclidean distance formula.
+   * Looks up the nearest data point using the internal quadtree.
+   *
+   * Note that for performance reasons, the optional filter is **DESTRUCTIVE**
```
Comment (hellochar) [inline src/utils/entityStore.ts]: So calling `entityNearest` mutates the quadtree? Is the expectation that this is only called once per call to addAll?

**Review by hellochar — APPROVED** [review]
Had some questions but looks good in general

**Review by leebyp — CHANGES_REQUESTED** [review]
blocking for panning (and zoom?) throttling - unless the removal of the getter makes this fine

File: src/plots/plot.ts (hunk 1 above)
Comment (themadcreator) [reply src/plots/plot.ts:398]: Yeah, we can probably remove it but previously we were clearing the cache here and i didn't want to miss it if it was needed. Since "clearing the cache" is just setting to `undefined` it's not gonna be slow

File: src/utils/entityStore.ts (hunk 3 above)
Comment (themadcreator) [reply src/utils/entityStore.ts]: It does, which is why i made this comment. There are no guarantees about who will call entityNearest from the outside, but unfortunately creating a copy of the tree every time is quite expensive. What would be ideal is if we could just get the quadtree itself to do the filtering, but that's not how it's implemented

File: src/utils/entityStore.ts (hunk 2 above)
Comment (themadcreator) [reply src/utils/entityStore.ts]: Alright, i guess math.floor isnt so bad:

image

File: src/utils/entityStore.ts (hunk 3 above)
Comment (themadcreator) [reply src/utils/entityStore.ts]: Making a copy means this method takes 10-20msec, whereas without the copy it take <1msec. Thoughts?

File: src/plots/plot.ts (hunk 1 above)
Comment (leebyp) [reply src/plots/plot.ts:398]: we weren't clearing it here originally

**Comment by themadcreator** [comment]
Remaining tasks are 
- [x] defer resetting entitystore on scale update
- [x] use bounds at entity store build time not nearest query time to avoid destructive update

File: src/plots/linePlot.ts [hunk 4]
```diff
@@ -451,7 +451,7 @@ export class Line<X> extends XYPlot<X, number> {
 
     const chartBounds = this.bounds();
     this.entities().forEach((entity) => {
-      if (!this._entityVisibleOnPlot(entity, chartBounds)) {
+      if (!Utils.Math.within(entity.position, chartBounds)) {
```
Comment (leebyp) [inline src/plots/linePlot.ts:454]: oh i guess we can just replace `this._entityVisibleOnPlot` with the math util in `plot.ts` too

File: src/utils/entityStore.ts [hunk 5]
```diff
@@ -3,95 +3,94 @@
...
 }
 
 /**
- * Array-backed implementation of {EntityStore}
+ * Implementation of {IEntityStore} that uses an array for easy iteration as
+ * well as a quad tree for fast nearest-point queries.
+ *
+ * Note that if the position of your entities changes, you MUST rebuild the
+ * entity store for the `entityNearest` method to work since the quadtree does
+ * not know that its nodes have moved.
```
Comment (leebyp) [inline src/utils/entityStore.ts:58]: `and may need to re-filter on the bounds`

**Review by leebyp — APPROVED** [review]

File: src/utils/entityStore.ts (hunk 5 above)
Comment (themadcreator) [reply src/utils/entityStore.ts:58]: yeah but im pretty clear about that in the comment on .addAll and entityNearest

File: src/plots/linePlot.ts (hunk 4 above)
Comment (themadcreator) [reply src/plots/linePlot.ts:454]: yeah i did that which is why i also had to change this here
